In [2]:
import numpy as np

In [29]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
np.ones((2,3,4))#生成一个二维的三行四列 ，值全为1的数组

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [33]:
np.random.randint(1,20,size=(4,5))

array([[19, 11, 16,  5,  2],
       [14, 11, 12, 15, 18],
       [19,  5, 16, 16,  3],
       [ 7, 11, 10,  9, 19]])

In [34]:
np.arange(1,9,2)

array([1, 3, 5, 7])

In [38]:
#生成等差数列
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [36]:
#生成等比数列
np.logspace(0,1,3,base=2)#表示在2的0次方和2的1次方之间生成3个等比数列

array([1.        , 1.41421356, 2.        ])

In [40]:
np.random.rand(2,3)*10

array([[7.96713998, 5.48583742, 6.92280715],
       [5.48410045, 1.45923542, 4.50518704]])

In [52]:
# randint(low, high=None, size=None, dtype='l')
# shape为ndim的属性
# dtype判断元素类型
a=np.random.randint(1,5,size=(2,3))
print(a)
print(a.shape)
print(a.dtype)

[[1 1 2]
 [3 1 2]]
(2, 3)
int32


##### 修改形状

reshape修改复制后的形状

shape在原本的基础上修改

In [56]:
arr=np.random.randint(1,5,8)
arr

array([1, 3, 3, 3, 1, 1, 4, 1])

In [57]:
arr.reshape(2,4)
arr

array([1, 3, 3, 3, 1, 1, 4, 1])

In [58]:
arr.shape=(4,2)
arr

array([[1, 3],
       [3, 3],
       [1, 1],
       [4, 1]])

##### ndarry运算
矩阵积

In [68]:
arr01 = np.random.randint(1,3,size=(2,2))
arr02 = np.random.randint(2,4,size=(2,1))
print(arr01)
print(arr02)
dot = np.dot(arr01,arr02)
print(dot)
dot

[[1 1]
 [2 1]]
[[3]
 [3]]
[[6]
 [9]]


array([[6],
       [9]])

* 切片

In [70]:
arry10=np.random.randint(1,20,size=(4,2,4))
arry10

array([[[15, 12,  9,  5],
        [15,  5, 14, 13]],

       [[17, 18, 14,  1],
        [16,  2, 18, 14]],

       [[16, 16,  4,  7],
        [13, 14,  1, 10]],

       [[ 3,  8, 12, 13],
        [ 6, 16,  6,  2]]])

In [71]:
arry10[2:,0,1:3]

array([[16,  4],
       [ 8, 12]])

In [72]:
arry10[[True,False,False,False]]

array([[[15, 12,  9,  5],
        [15,  5, 14, 13]]])

* 矩阵转置

In [78]:
# arry10.transpose
arry10.T

array([[[15, 17, 16,  3],
        [15, 16, 13,  6]],

       [[12, 18, 16,  8],
        [ 5,  2, 14, 16]],

       [[ 9, 14,  4, 12],
        [14, 18,  1,  6]],

       [[ 5,  1,  7, 13],
        [13, 14, 10,  2]]])

##### 聚合函数
求平均值、方差、标准差

In [79]:
#二元函数比较大小np.greater(arr1,arr2),返回的是布尔类型的值
np.greater([4,2],[2,2])

array([ True, False])

In [80]:
#求平均值
arr1=np.array([[1,2,3,4],[2,3,4,5]])
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [81]:
arr1.mean(axis=0)#求每一列的平均值

array([1.5, 2.5, 3.5, 4.5])

In [82]:
arr1.mean(axis=1)#求每一行的平均值

array([2.5, 3.5])

In [83]:
#求方差
np.var(arr,axis=1)

array([1.  , 0.  , 0.  , 2.25])

In [84]:
#求标准差
arr1.std(axis=1)

array([1.11803399, 1.11803399])

In [87]:
#np.where(condition,arr1,arr2)
#例子：将np.nan换成0
a1=np.array([
    [1,2,np.NaN],
    [1,2,np.pi],
    [1,2,np.e],
])
a1

array([[1.        , 2.        ,        nan],
       [1.        , 2.        , 3.14159265],
       [1.        , 2.        , 2.71828183]])

In [88]:
condition=np.isnan(a1)
np.where(condition,0,a1)

array([[1.        , 2.        , 0.        ],
       [1.        , 2.        , 3.14159265],
       [1.        , 2.        , 2.71828183]])

* np.unique去重复操作

In [3]:
arr2=np.array([0,1,2,11,1,1])
np.unique(arr2)

array([ 0,  1,  2, 11])